config/routes.rb
Rails.application.routes.draw do
  get 'lists/index'
  get 'lists/show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, except: [:destroy] do
      resources :movies
    end
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: [:list]}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
# piss off rubocop
class BookmarksController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @allmovies = Movie.all
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def update
    @bookmark.update(bookmark_params)
    redirect_to list_path(@bookmark)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :load_lists, only: [:index, :create]

  def index
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @allmovies = Movie.all
    @bookmark = Bookmark.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      # use this to redirect to new list instead of stay on same page
      # redirect_to list_path(@list)
      redirect_to lists_path
    else
      render 'index', status: :unprocessable_entity
    end
  end

  private

  def load_lists
    @lists = List.all
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="background-color: #F6F4EB;">
    <div class="d-flex flex-wrap justify-content-center align-items-center my-3" style="height: 100%; min-height: 95vh;">
      <div class="card text-center text-white p-3 shadow" style="background-color: #749BC2; border-radius: 10px;">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Playlists</h1>

<div class="lists-container overflow-auto" style="max-height: 200px;">
  <% @lists.each do |list| %>
    <div class="card shadow my-2" style="border-radius: 10px;">
      <div class="card-body py-1" style="background-color: #4682A9; border-radius: 10px;">
        <h6 class="my-2"><%= link_to list.name, list_path(list), class: "text-decoration-none" %></h6>
      </div>
    </div>
  <% end %>
</div>
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit class: "btn btn-light mt-1" %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<% if @list.movies.empty? %>
  <div class="d-flex flex-column">
    <div class="d-flex flex-wrap justify-content-center my-3">
      <div class="lists-container overflow-auto" style="max-height: 300px; max-width: 400px;">
<% else %>
  <div class="d-flex flex-wrap justify-content-between my-3">
    <div class="d-flex flex-column">
      <h5>My Bookmarks</h5>
      <div class="lists-container overflow-auto" style="max-height: 300px; width: 400px; margin-right: 50px;">
<% end %>

        <% @list.movies.each do |movie| %>
          <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
          <div class="mb-3" style="background-color: #F6F4EB; border-radius: 10px;">
            <div class="d-flex align-items-start" style="background-color: #222; border-radius: 10px 10px 0 0; color: #FFF;">
              <%= image_tag movie.poster_url %>
              <div class="d-flex flex-column justify-content-center" style="width: 100%;">
                <div class="d-flex justify-content-center align-items-center">
                  <h6 class="col-9" style="font-size: 14px;"><%= movie.title %></h6>
                  <p class="col-2 d-flex flex-column align-items-end mt-1" style="font-size: 12px;"><%= movie.rating %><i class="fas fa-star star-yellow"></i></p>
                </div>
                <div class="overflow-auto d-flex justify-content-center" style="max-height: 80px;">
                  <p class="p-3 my-1 text-center" style="font-size: 12px;"><%= movie.overview %></p>
                </div>
              </div>
            </div>


            <div class="overflow-auto flex-column d-flex justify-content-center px-3 border" style="max-height: 80px; background-color: #EFF5F5; color: #222;">
              <p class="p-1 my-1 text-center" style="font-size: 12px;"><%= bookmark.comment %></p>
            </div>

            <%= button_to "Delete", bookmark_path(bookmark), method: :delete, class: "btn btn-flat btn-sm", data: { turbo_confirm: "Are you sure?" } , style: "margin-top: 4px; margin-bottom: 4px;" %>

          </div>
        <% end %>
      </div>
    </div>

    <div class="d-flex flex-column">
      <h5>Look through movies</h5>
      <div class="movies-container overflow-auto" style="max-height: 300px; width: 400px;">
        <% @allmovies.each do |movie| %>
          <div class="border mb-3" style="background-color: #F6F4EB; border-radius: 10px; color: black;">
            <div class="d-flex align-items-start" style="background-color: #222; border-radius: 10px 10px 0 0; color: #FFF;">
              <%= image_tag movie.poster_url %>
              <div class="d-flex flex-column justify-content-center" style="width: 100%;">
                <div class="d-flex justify-content-center align-items-center">
                  <h6 class="col-9" style="font-size: 14px;"><%= movie.title %></h6>
                  <p class="col-2 d-flex flex-column align-items-end mt-1" style="font-size: 12px;"><%= movie.rating %><i class="fas fa-star star-yellow"></i></p>
                </div>
                <div class="overflow-auto d-flex justify-content-center" style="max-height: 80px;">
                  <p class="p-3 my-1 text-center" style="font-size: 12px;"><%= movie.overview %></p>
                </div>
              </div>
            </div>

            <%= simple_form_for [@list, @bookmark] do |f| %>
              <%= f.hidden_field :movie_id, value: movie.id %>
              <%= f.input :comment, placeholder: 'Enter a comment about the movie', class: "form-control",
                          label_html: { style: "font-size: 12px;" },
                          input_html: { style: "font-size: 12px;" } %>
              <%= f.submit "Add to List", class: "btn btn-flat btn-sm", style: "margin-top: -12px; margin-bottom: 6px;" %>
            <% end %>

          </div>
        <% end %>
      </div> <!-- Close the second "if" div's container -->
    </div>
  </div> <!-- Close the main container div -->

  <%= button_to "Go Back", lists_path, method: :get, class: "btn btn-light", style: "margin-top: 14px;" %>